[package]
name = "homework5"
version = "0.1.0"
authors = ["lzw65 <372208209@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
